### ISSUE TITLE
Is there a standalone Dashboard to use with this package?

### ISSUE THREAD

**Issue by mbpcoder** [servocoder/lumen-horizon#3]
Hi,
Is there a standalone Dashboard to use with this package?

**Comment by mbpcoder** [comment]
@servocoder  any suggestion?

**Comment by psolom** [comment]
As it's described in [readme.md](https://github.com/servocoder/lumen-horizon#introduction), "you can install another Laravel application with Horizon on the board to watch jobs and metrics of your Lumen applications". Laravel app should hook up and watch supervisor processes that you run at your Lumen app.

**Comment by mbpcoder** [comment]
thanks.
